
Duo DigIn - Terms of Service


This is a Legal Agreement (“Agreement”) between you (“You”, “you”, “Participant” or “Customer”) and Duo World Inc., (“DuoWorld”), having place of business at 170S, Green Valley Parkway, Suite 300, Henderson, Nevada 89012, United States of America. If You are entering into this Agreement on behalf of a company or other legal entity, You represent and warrant that (i) You have full legal authority to bind that company or legal entity to the terms of this Agreement; (ii) You have read and understand this Agreement; (iii) You agree on behalf of the company or legal entity to this Agreement.

1. Acceptance DuoWorld provides the defined below Products to you subject to the following terms and conditions (Terms of Service) in this Agreement, which may be updated by DuoWorld from time to time without notice to you. You can review the most current version of this Agreement at any time at ………………………… By clicking on the “I agree” (or similar button) that is presented to you at the time of your Order, or Your registration for, or by using the Products or by accessing DuoWorld Web Site, you accept and agree to be bound by all of these Terms of Service of this Agreement. If you do not agree to all of these Terms of Service, You must not use the Products or access the DuoWorld Web Site.

2. Scope of the Agreement
DuoWorld provides DUO DIGIN (“Product” or “Products”) and this Product is offered and provided subject to the Terms of Service of this Agreement and shall govern your initial purchase as well as any future purchasers made by you that reference this Agreement. This Agreement includes our Acceptable Use Policy, Privacy Policy and any other referenced policies and attachments. Customer shall connect to the Product using any Internet browser supported by the Product. Customer is responsible for obtaining access to the Internet and the hardware/equipment necessary to access the Product. Unless explicitly stated otherwise, any new features that augment or enhance the current Services, including the release of new DuoWorld properties, shall be subject to this Agreement.

3. Description of the Service
DUO DIGIN is designed to simplify business analytics for complex data by providing a complete solution for preparing, analyzing, reporting, visualizing, dashboards, algorithms and workflow capabilities big or disparate datasets for business intelligence. This Agreement governs (a) DuoWorld’s commercially available downloadable software Products (currently designated as "Server" deployments) (“Software”), (b) DuoWorld’s hosted or cloud-based solutions (currently designated as "Cloud" deployments) (“Hosted Services”), and (c) any related support or maintenance services provided by DuoWorld. Software and Hosted Services, together with related Documentation, are referred to as “Products”. The Products and their permitted use are further described in DuoWorld’s standard documentation (“Documentation”).

4. Your Obligation of Registration
(a) In order to place orders or access the website or use the product or receive any service offered by DuoWorld you must have an Account. You are responsible for the information provides to create the Account, the security of the password for the Account, any use of and all actions taken through your Account. Any registration information that you provide to us must be accurate, current and complete. You must also update your information so that DuoWorld may send notices, statements and other information to you by email or through your account. If you provide any information that is untrue, inaccurate, not current or incomplete, or DuoWorld has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, DuoWorld has the right to suspend or terminate your account and refuse any and all current or future use of the Product (or any portion thereof). You agree to (a) immediately notify DuoWorld of any unauthorized use of your password or account or any other breach of security, and (b) ensure that you exit from your account at the end of each session. DuoWorld cannot and will not be liable for any loss or damage arising from your failure to comply with this Section.

(b) Access to the Product is only available to the Customer and the Users to whom the Customer grants access, subject to the Customer making the applicable payments for the Product under this Agreement.

(c) Usernames and passwords are personal, and are to be considered part of Confidential Information of Customer. The Customer is at all times fully liable for all acts and omissions by Users whom the Customer has granted access and agrees to indemnify DuoWorld for all claims and losses related to such acts and omissions.

5. Orders
DuoWorld’s Product ordering documentation (“Order”) will specify your authorized scope of use for the Products, which may include: (a) number and type of Authorized Users (as defined below), (b) storage or capacity (for Hosted Services) (c), numbers of licenses, copies or instances (for Software),or (d) other restrictions or billable units. The term “Order” also includes any applicable Product or Support and Maintenance renewal, or purchases you make to increase or upgrade your Scope of Use.

6. Authorized Users.
(a) Authorized Users are only the specific individuals for whom you have paid the required fees and whom you designate through the applicable Product may access and use the Products. Authorized Users may be you or your Affiliates’ employees, representatives, consultants, contractors, agents, or other third parties who are acting for your benefit or on your behalf. Some Products may allow you to designate different types of Authorized Users, in which case pricing and functionality may vary according to the type of Authorized User. You are responsible for compliance with this Agreement by all Authorized Users. All use of Products by you and your Authorized Users must be within the Scope of Use and solely for the benefit of you or your Affiliates.

(b) You may increase the number of Authorized Users permitted to access your instance of the Product by placing a new Order or, in some cases, directly through the Product. In all cases, you must pay the applicable fee for the increased number of Authorized Users.

7. Software License Terms
(a) License Right - DuoWorld grants you a non-exclusive, non-sublicenseable and non-transferable license to install and use the Software during the applicable License Term (“License Term”) in accordance
with your applicable Scope of Use and the Documentation subject to the terms and conditions of this Agreement. The term of each Software license will be specified in your Order. Your License Term will end upon any termination of this Agreement, even if it is identified as “perpetual” or if no expiration date is specified in your Order. In order to operate the software, a license key is required and such will be delivered as described in Section 11 (Return of the Products and Delivery).

(b) Modifications made by You - Subject to the terms and conditions of this Agreement: (1) for any components of the Software provided by DuoWorld in source code form, and to the extent permitted in the Documentation, you may modify such source code solely for purposes of developing bug fixes, customizations and additional features for the Software and (2) you may also modify the Documentation to reflect your permitted modifications of the Software source code or the particular use of the Products within your institution. Any modified source code or Documentation constitutes “Modifications done by You”. You may solely use Modifications done by You with respect to your own instances in support of your permitted use of the Software. You shall not distribute the code to Your Modifications to any third party. Notwithstanding anything in this Agreement to the contrary, DuoWorld has no support, warranty, indemnification or other obligation or liability with respect to Modifications made by You or their combination, interaction or use with DuoWorld Products. You shall indemnify, defend and hold us harmless from and against any and all claims, costs, damages, losses, liabilities and expenses (including reasonable attorneys’ fees and costs) arising out of or in connection with any claim brought against DuoWorld by a third party relating to Your Modifications (including but not limited to any representations or warranties you make about Modifications made by You or the Software) or your breach of this Section.

(c) Compliance – Customer is solely responsible for its Customer Data and Applications comply with DuoWorld AUP. DuoWorld reserves the right to review the Customer Data and Applications for the strict compliance with the DuoWorld AUP. Customer is responsible for ensuring all Customer end users comply with Customer’s Obligation under DuoWorld AUP.

(d) Acknowledgement - In any use of the Product, where applicable you must include the following acknowledgement to DuoWorld on all user interfaces in the following format: “Powered by DuoWorld,” which must in every case include a hyperlink to ……………………., and which must be in the same format as delivered in the Software.

8. Terms for Hosted Services (where applicable only)
(a) Access to the Hosted Services - Subject to the terms and conditions of this Agreement, DuoWorld grants you a non-exclusive right to access and use the Hosted Services during the applicable Subscription Term in accordance with this Agreement, your applicable Scope of Use and the Documentation. You acknowledge that DuoWorld Hosted Services are on-line, subscription-based products and that DuoWorld may make changes to the Hosted Services from time to time.

(b) Subscription Terms and Renewals – As specified in your Order, Hosted Services are provided on a subscription basis for a set term (“Subscription Term”). All subscriptions will automatically renew for periods equal to your initial Subscription Term (and you will be charged at the then-current rates and applicable taxes and levies) except as otherwise specified in your Order, unless you cancel your subscription through your account at ……………... If you cancel, your subscription will terminate at the end of then-current billing cycle. You shall not be entitled to any credits or refunds for amounts accrued or paid prior to such termination.

(c) (i) Your Content - “Your Content” means any and all information, data, text, software, code, music, sound, photographs, graphics, video, images or other materials of any type that you upload, submit, post or otherwise transmit to or through Hosted Services. You will retain all right, title and interest in and to Your Content in the form provided to DuoWorld and shall have sole responsibility of the persons from whom such content originated. Subject to the terms of this Agreement, you hereby grant to DuoWorld a non-exclusive, worldwide, royalty-free right to (a) collect, use, copy, store, transmit, modify and create derivative works of Your Content, in each case solely to the extent necessary to provide the applicable Hosted Service to you and (b) for Hosted Services that enable you to share Your Content or interact with other third parties, to distribute and publicly perform and display Your Content as you (or your Authorized Users) direct or enable through the Hosted Service. DuoWorld shall have the right to access your account in order to respond to your support requests.

(ii) General Responsibility - You must ensure at all times that your use of Hosted Services and all Your Content is compliant with DuoWorld Acceptable Use Policy and all applicable local, state, federal and international laws and regulations (“Laws”). You represent and warrant that: (i) you have obtained all necessary rights, releases and permissions to provide all Your Content to DuoWorld and to grant the rights granted to DuoWorld under this Agreement and (ii) Your Content is transfer to and use by DuoWorld as authorized by you under this Agreement and do not violate any Laws (including without limitation those relating to export control and electronic communications) or rights of any third party, including without limitation any intellectual property rights, rights of privacy, or rights of publicity, and any use, collection and disclosure authorized herein is not inconsistent with the terms of any applicable privacy policies. You understand that by using the Hosted Services, you may be exposed to Content that is offensive, indecent or objectionable. Under no circumstances DuoWorld be liable in any way for any Content, including, but not limited to, any errors or omissions in any Content, or any loss or damage of any kind incurred as a result of the use of any Content posted, emailed, transmitted or otherwise made available via the service. DuoWorld assumes no responsibility or liability for Your Content, and you shall be solely responsible for Your Content and the consequences of uploading, posting, using, disclosing, storing, transmitting it or otherwise make available via the service.

(iii) Indemnity for Your Content - You will defend, indemnify and hold harmless DuoWorld from and against any loss, cost, liability or damage, including attorneys’ fees, for which DuoWorld becomes liable arising from or relating to any claim relating to Your Content, including but not limited to any claim brought by a third party alleging that Your Content, or your use of the Hosted Services in breach of this Agreement, infringes or misappropriates the intellectual property rights of a third party or violates applicable law. This indemnification obligation is subject to your receiving (i) prompt written notice of such claim (but in any event notice in sufficient time for you to respond without prejudice); (ii) the exclusive right to control and direct the investigation, defense, or settlement of such claim; and (iii) all reasonable necessary cooperation of DuoWorld at your expense.

(iv) Sensitive Data - You agree not submit to the Hosted Services (or use the Hosted Services to collect): (i) any personally identifiable information, except as necessary for the establishment of your DuoWorld account; (ii) any patient, medical or other protected health information regulated by HIPAA (“HIPAA” means the Health Insurance Portability and Accountability Act, as amended and supplemented) or any similar federal or state laws, rules or regulations; or (iii) any other information subject to regulation or protection under specific laws. Notwithstanding any other provision to the contrary, DuoWorld has no liability under this Agreement for Sensitive Data.

(d) Data Accuracy and Relevancy - DuoWorld shall not be responsible for the accuracy, relevancy, correctness, and completeness of Your Content that use for business intelligence purpose. You acknowledge that such Your Content may be inaccurate, irrelevant, incorrect or incomplete and DuoWorld expressly exclude any such liability for inaccurate, irrelevant, incorrect or incomplete Your Content to the fullest extent permitted by law.

(e) Safety & Security – DuoWorld from time to time implements security procedures to help to protect Your Content from security attacks. However, we are not responsible for any of Your Content lost, altered, intercepted or stored across such networks, as you understand that use of the Hosted Services necessarily involves transmission of Your Content over networks that are not owned, operated or controlled by DuoWorld. DuoWorld shall not be responsible for and cannot guarantee for an error-free security procedures, the transmissions of Your Content will always be secure or that unauthorized third parties will never be able to defeat DuoWorld security measures or those of our third party service providers.

(f) Storage Capacity – DuoWorld shall have the right and discretion to impose new, or to modify existing, storage limits for the Hosted Services at any time with or without notice to you. A particular Hosted Service may have storage limits and these limits are described in the services descriptions on our websites or in the Documentation for the particular Hosted Service. DuoWorld reserves the right to charge for additional storage or overage fees at the rates specified on DuoWorld website.

(g) Deletion of the Content at End of Subscription Term - DuoWorld shall remove or delete Your Content within a reasonable period of time after the termination of your Subscription Term.

(h) Suspension and Removal – DuoWorld has no obligation to monitor any Content uploaded to the Hosted Services. Nonetheless, if DuoWorld deem such action necessary based on your violation of this Agreement, DuoWorld shall (i) remove Your Content from the Hosted Services or (ii) suspend your access to the Hosted Services. Generally DuoWorld will alert you when taking such action and give you a reasonable opportunity to cure your breach, but if DuoWorld determine that your actions endanger the operation of the Hosted Service or other users, DuoWorld may suspend your access immediately without notice. You will continue to be charged for the Hosted Service during any suspension period. DuoWorld have no liability to you for removing or deleting Your Content from or suspending your access to any Hosted Services as described in this section.

(i) Third-Party Links and Websites - Links on this Product to third-party websites are provided solely as a convenience to you. If you use these links, you will leave this Site. DuoWorld has not reviewed these third-party sites and does not control and is not responsible for any of these sites or their content. Thus, DuoWorld does not endorse or make any representations about them, or any information, software or other products or materials found there, or any results that may be obtained from using them. If you decide to access any of the third-party websites linked to this Product, you do this entirely at your own risk.

(j) Final Outcome/Result - Under no circumstances DuoWorld shall liable for the net results, final outcome obtained by using the Product.

(k) Your Use of the Product - Your use of this Product is entirely at your own risk, for which DuoWorld shall not be liable. It shall be your own responsibility to ensure that any services or information available through this Product meet your specific requirements.

9. Support and Maintenance
DuoWorld may provide the support and maintenance services for the Products described in the DuoWorld Support Policy (“Support and Maintenance”) during the period for which you have paid the applicable fee. Support and Maintenance is subject to the terms of the DuoWorld Support Policy and as specified in your Order DuoWorld will provide the support level during the support term. The DuoWorld Support Policy may be modified by DuoWorld from time to time to reflect process improvements or changing practices. Support and Maintenance for Software includes access to New Releases, if and when available.

10. Training
As stated in the Order purchased by you DuoWorld will provide training services in an Order in accordance with the descriptions and conditions for those services set forth in the Order and the accompanying service descriptions. DuoWorld shall retain all right, title and interest in and to any materials, deliverables, modifications, derivative works or developments related to any training services we provide (“Training Materials”). Any and all Training Materials provided to you may be used only in connection with the Products subject to the same use restrictions for the Products.

11. Return of the Product and Delivery
(a) As part of our commitment to customer satisfaction, it is DuoWorld allow the customers to return a Product within 30 days of payment for any reason or no reason and to receive a refund of the amount paid for the returned Product. In the context of Software, a return means that we will disable the license key that allowed the Software to operate. In the context of Hosted Services, a return means that we will disable access to the Hosted Service. DuoWorld will not accept returns after the 30-day return period. You understand that DuoWorld may change this practice in the future in accordance with Section 25 (Modifications).

(b) DuoWorld will deliver the applicable license keys (in the case of Software) or login instructions (in the case of Hosted Services) to the email addresses specified in your Order when DuoWorld have received payment of the applicable fees. All deliveries under this Agreement will be electronic. For the avoidance of doubt, you are responsible for installation of any Software, and you acknowledge that DuoWorld has no further delivery obligation with respect to the Software after delivery of the license keys.

12. Financial Terms
(a) Payment – You agree to pay all fees in accordance with each Order. Unless otherwise specified in your Order, you will pay all amounts in U.S. dollars at the time you place your Order. All amounts are non-refundable, non-cancelable and non-creditable. In making payments, you acknowledge that you are not relying on future availability of any Products beyond the current License Term or any Product upgrades or feature enhancements. You agree to pay for the Authorized Users you add during the applicable License Term. You will be charged for the increased number of Authorized Users by you pursuant to the then-currently applicable rates in your next billing cycle. You agree that DuoWorld may bill your credit card for renewals, additional users, and unpaid fees, as applicable. In case of non-payment for any reason or any violation of these terms, DuoWorld shall be entitled – without liability – to immediately bar Customer’s access to use the Products.

(b) Taxes - Your payments under this Agreement exclude any taxes or duties payable in respect of the Products in the jurisdiction where the payment is either made or received. To the extent that any such taxes or duties are payable by DuoWorld, you must pay to DuoWorld the amount of such taxes or
addition to any fees owed under this Agreement. Notwithstanding the foregoing, you may have obtained an exemption from relevant taxes or duties as of the time such taxes or duties are levied or assessed. In that case, you will have the right to provide to DuoWorld any such exemption information, and DuoWorld will use reasonable efforts to provide such invoicing documents as may enable you to obtain a refund or credit for the amount so paid from any relevant revenue authority if such a refund or credit is available.

(c) DuoWorld reserves the right to change the license fee from time to time without notification to you.

13. Free-Plan Products
DuoWorld may offer certain Products to you at no charge, including free accounts, trial use, and access to Beta Versions as defined below (“Free-Plan Products”). Your use of Free-Plan Products is subject to any additional terms that DuoWorld specify and is only permitted for the period designated by DuoWorld. You may not use Free-Plan Products for competitive analysis or similar purposes. DuoWorld may terminate your right to use Free-Plan Products at any time and for any reason at DuoWorld’s sole discretion, without liability to you. You understand that any pre-release and beta products DuoWorld make available (“Beta Versions”) are still under development, may be inoperable or incomplete and are likely to contain more errors and bugs than generally available Products. DuoWorld will not generally made available all Beta Versions. In certain circumstances, DuoWorld may charge a fee in order to allow you to access Beta Versions, but the Beta Versions will still remain subject to this Section (Free-Plan Products). All information regarding the characteristics, features or performance of Beta Versions constitutes DuoWorld’s Confidential Information. To the maximum extent permitted by applicable law, DuoWorld disclaim all obligations or liabilities with respect to Free-Plan Products, including any Support and Maintenance, warranty, and indemnity obligations.

14. Limitations on Use
Except as otherwise expressly permitted in this Agreement, you shall not: (a) rent, lease, reproduce, modify, adapt, create derivative works of, distribute, sell, sublicense, transfer, or provide access to the Products to a third party, (b) reverse engineer, disassemble, decompile, translate, or otherwise seek to obtain or derive the source code, underlying ideas, algorithms, file formats or non-public APIs to any Products, except as permitted by law, (c) incorporate any Products into a product or service you provide to a third party, (d) interfere with any license key mechanism in the Products or otherwise circumvent mechanisms in the Products intended to limit your use, (e) use the Products for the benefit of any third party, (f) remove or obscure any proprietary or other notices contained in any Product, or (g) publicly disseminate information regarding the performance of the Products.

15. Customer Developments
Notwithstanding anything in this Agreement to the contrary, DuoWorld has no support, warranty, indemnification or other obligation or liability with respect to your Customer Developments or their combination, interaction or use with the Products. You shall indemnify, defend and hold us harmless from and against any and all claims, costs, damages, losses, liabilities and expenses (including reasonable attorneys’ fees and costs) arising out of or in connection with any claim brought against us by 

a third party relating to your Customer Developments (including but not limited to any representations or warranties you make about your Customer Developments) or your breach of this section.
16. Ownership
Products are made available on a limited license or access basis, and no ownership right is conveyed to you, irrespective of the use of terms such as “purchase” or “sale”. DuoWorld have and retain all right, title and interest, including all intellectual property rights, in and to the Products (including all Free-Plan Products),
any and all related or underlying technology, and any modifications or derivative works of the foregoing created by or for DuoWorld.

17. Confidentiality
(a) Except as otherwise set forth in this Agreement, each party agrees that any and all data or information that is of value to disclosing party (“Disclosing Party”), and is not generally known in the industry or to competitors of Disclosing Party, and includes, but is not limited to, all codes, inventions, know-how, strategies, business, technical, financial information, business processes, specifications, research, software, trade secrets, discoveries, ideas etc., disclosed to such party (“Receiving Party”) by the Disclosing Party constitute the confidential property of the Disclosing Party ("Confidential Information"), provided that it is identified as confidential at the time of disclosure. Any DuoWorld Technology and any performance information relating to the Products shall be deemed Confidential Information of DuoWorld without any marking or further designation. Except as expressly authorized herein, the Receiving Party will hold in confidence and not use or disclose any Confidential Information. The Receiving Party's nondisclosure obligation shall not apply to information which the Receiving Party can document: (i) was rightfully in its possession or known to it prior to receipt of the Confidential Information; (ii) is or has become public knowledge through no fault of the Receiving Party; (iii) is rightfully obtained by the Receiving Party from a third party without breach of any confidentiality obligation; (iv) is independently developed by employees of the Receiving Party who had no access to such information or (v) is approved by the Disclosing Party in writing for release.

(b) The Receiving Party may also disclose Confidential Information if so required pursuant to a regulation, law or court order (but only to the minimum extent required to comply with such regulation or order and with advance notice to the Disclosing Party).

(c) The Receiving Party acknowledges that disclosure of Confidential Information would cause substantial harm for which damages alone would not be a sufficient remedy, and therefore that upon any such disclosure by the Receiving Party the Disclosing Party shall be entitled to appropriate equitable relief in addition to whatever other remedies it might have at law. For the avoidance of doubt, this Section shall not operate as a separate warranty with respect to the operation of any Product.

18. Term and Termination
This Agreement is in effect for as long as you have a valid License Term (the “Term”), unless sooner terminated as permitted in this Agreement. Either party may terminate this Agreement before the expiration of the Term if the other party materially breaches any of the terms of this Agreement and does not cure the breach within thirty (30) days after written notice of the breach. Either party may also terminate the Agreement before the expiration of the Term if the other party ceases to operate, declares bankruptcy, or becomes insolvent or otherwise unable to meet its financial obligations. You may terminate this Agreement at any time with notice to DuoWorld, but you shall not be entitled to any credits or refunds as a result of convenience termination for prepaid but unused Software, or Support and Maintenance. Except where an exclusive remedy may be specified in this Agreement, the exercise by either party of any remedy, including termination, will be without prejudice to any other remedies it may have under this Agreement, by law, or otherwise. Once the Agreement terminates, you (and your Authorized Users) will no longer have any right to use or access any Products, or any information or materials that we make available to you under this Agreement, including DuoWorld Confidential Information. You are required to delete any of the foregoing from your systems as applicable (including any third party systems operated on your behalf) and provide
written certification to us that you have done so at our request. The following provisions will survive any termination or expiration of this Agreement: Sections 8 (Customer Obligation), 11(a) (Payment), 11(b) (Taxes), 12 (Free Plan Products) (disclaimers and use restrictions only), 13 (Limitation on the use), 14 (Ownership), 15 (Confidentiality), 16 (Term and Termination), 17 (Warranty Disclaimer), 18 (Limitation of Liability), 19 (Third Party Vendor Products), 21 (Dispute Resolution), and 24 (General Provisions).

19. Warranty Disclaimer
THIS SITE, ALL SERVICE AND CONTENT ARE PROVIDED “AS IS,” AND “AS AVAILABLE” BASIS AND DUOWORLD AND ITS SUBSIDIARIES, AFFILIATES, OFFICERS, EMPLOYEES, AGENTS, PARTNERS, SUPPLIERS AND LICENSORS EXPRESSLY DISCLAIM ANY AND ALL WARRANTIES AND REPRESENTATIONS OF ANY KIND, INCLUDING ANY WARRANTY OF ACCURACY, NON-INFRINGEMENT, TITLE, FITNESS FOR A PARTICULAR PURPOSE, FUNCTIONALITY, OR MERCHANTABILITY, WHETHER EXPRESS, IMPLIED, OR STATUTORY. YOU MAY HAVE OTHER STATUTORY RIGHTS, BUT THE DURATION OF STATUTORILY REQUIRED WARRANTIES, IF ANY, SHALL BE LIMITED TO THE SHORTEST PERIOD PERMITTED BY LAW. ALL INFORMATION PROVIDED ON THE SITE IS SUBJECT TO CHANGE WITHOUT NOTICE. DUOWORLD CANNOT ENSURE THAT ANY FILES OR OTHER DATA YOU DOWNLOAD FROM THE SITE WILL BE FREE OF VIRUSES OR CONTAMINATION OR DESTRUCTIVE FEATURES. DUOWORLD DISCLAIMS ANY AND ALL LIABILITY FOR THE ACTS, OMISSIONS AND CONDUCT OF ANY THIRD PARTIES IN CONNECTION WITH OR RELATED TO YOUR USE OF THE SITE AND/OR ANY DUOWORLD SERVICES. YOU ASSUME TOTAL RESPONSIBILITY FOR YOUR USE OF THE SITE AND ANY LINKED SITES. DUOWORLD SHALL NOT BE LIABLE FOR DELAYS, INTERRUPTIONS, SERVICE FAILURES AND OTHER PROBLEMS INHERENT IN USE OF THE INTERNET AND ELECTRONIC COMMUNICATIONS OR OTHER SYSTEMS OUTSIDE THE REASONABLE CONTROL OF DUOWORLD. TO THE MAXIMUM EXTENT PERMITTED BY LAW, NEITHER DUOWORLD NOR ANY OF ITS THIRD PARTY SUPPLIERS MAKES ANY REPRESENTATION, WARRANTY OR GUARANTEE AS TO THE RELIABILITY, TIMELINESS, QUALITY, SUITABILITY, TRUTH, AVAILABILITY, ACCURACY OR COMPLETENESS OF ANY PRODUCTS OR ANY CONTENT THEREIN OR GENERATED THEREWITH, OR THAT: (A) THE USE OF ANY SERVICES WILL BE SECURE, TIMELY, UNINTERRUPTED OR ERROR-FREE, OR THAT YOUR USE OF THIS SITE WILL PROVIDE SUFFICIENT RESULTS; (B) THE SERVICES WILL OPERATE IN COMBINATION WITH ANY OTHER HARDWARE, SOFTWARE, SYSTEM, OR DATA; (C) THE SERVICES (OR ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE PRODUCTS) WILL MEET YOUR REQUIREMENTS OR EXPECTATIONS; (D) ANY STORED DATA WILL BE ACCURATE OR RELIABLE OR THAT ANY STORED DATA WILL NOT BE LOST OR CORRUPTED; (E) ANY ERRORS OR DEFECTS WILL BE CORRECTED; OR (F) THE SERVICES (OR ANY SERVER(S) THAT MAKE A HOSTED SERVICE AVAILABLE) ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.

20. Limitation of Liability
You expressly understand and agree that DuoWorld and its subsidiaries, affiliates, officers, employees, agents, partners and licensors shall not be liable to you for any direct, indirect, incidental, special, reliance, consequential or exemplary damages, including but not limited to, those resulting from lost profits, lost savings, lost goodwill, business interruption, lost data or other intangible losses (even if DuoWorld has been advised or informed of the possibility of such damages), regardless of the form of action, whether in contract , tort (including negligence) strict liability or otherwise, resulting from:

a) The use or the inability to use the Product;
b) The cost of procurement of substitute products or services resulting from any product, data, information or services purchased or obtained or messages received or transactions entered into through or from the service;
c) Interruption of business;
d) Lost or inaccurate data, unauthorized access to or alteration of your transmissions or data;
e) Failure of security mechanisms;
f) Any third party websites linked to the Product;
g) Statements or conduct of any third party on the service; or
h) Any other matter relating to the service.

Neither party’s aggregate liability to the other shall exceed the amount actually paid by you to DuoWorld for products and support and maintenance in the 6months immediately preceding the claim. This section 19 (limitation of liability) shall not apply to (1) amounts owed by you under any orders, (2) either party’s express indemnification obligations in this agreement, or (3) your breach of section 13 (Limitation on Use) or combining the products with open source software of third party code in DuoWorld products. To the maximum extent permitted by law, no suppliers of any third party components included in the products will be liable to you for any damages whatsoever. The parties agree that the limitations specified in this Section will survive and apply even if any limited remedy specified in this Agreement is found to have failed of its essential purpose.

21. Third Party Vendor Products
DuoWorld or third parties may from time to time make available to you (e.g., through the DuoWorld Marketplace) third-party products or services, including but not limited to Customer Developments and plugins as well as implementation, customization, training, and other consulting services. If you procure any of these third party products or services, you do so under a separate agreement (and exchange of data) solely between you and the third party vendor. DuoWorld does not warrant or support non- DuoWorld products or services, whether or not they are designated by DuoWorld as “verified” or otherwise, and disclaims all liability for such products or services. If you install or enable any third party products or services for use with DuoWorld products, you acknowledge that DuoWorld may allow the vendors of those products and services to access Your Content as required for the interoperation and support of such add-ons with the DuoWorld products. DuoWorld shall not be responsible for any disclosure, modification or deletion of Your Content resulting from any such access by third party product vendors.

22. IP Indemnification by DuoWorld
a) DuoWorld will defend you against any claim brought against you by a third party alleging that a Product, when used as authorized under this Agreement, infringes a United States or European Union patent or registered copyright (a “Claim”), and DuoWorld will indemnify you and hold you harmless against any damages and costs finally awarded by a court of competent jurisdiction or agreed to settlement by DuoWorld (including reasonable attorneys’ fees) arising out of a Claim, provided that we have received from you:
(i) prompt written notice of the claim (but in any event notice in sufficient time for us to respond without prejudice);
(ii) reasonable assistance in the defense and investigation of the claim, including providing us a copy of the claim and all relevant evidence in your possession, custody or control; and
(iii) the exclusive right to control and direct the investigation, defense, and settlement (if applicable) of the claim.
b) DuoWorld’s indemnification obligations above do not apply: (1) if the total aggregate fees received by DuoWorld with respect to your license to Software or subscription to Hosted Services in the 12 month period immediately preceding the claim is less than US$50,000; (2) if the Product is modified by any party other than DuoWorld, but solely to the extent the alleged infringement is caused by such modification; (3)
if the Product is used in combination with any non- DuoWorld product, software or equipment, but solely to the extent the alleged infringement is caused by such combination; (4) to unauthorized use of Products; (5) to any Claim arising as a result of (i) Your Content (or circumstances covered by your indemnification obligations in Section 8.C.iii (Indemnity for Your Content) or (ii) any third-party deliverables or components contained with the Products; (6) to any unsupported release of the Software; or (7) if you settle or make any admissions with respect to a claim without DuoWorld’s prior written consent.

23. Dispute Resolution
In the event of any controversy or claim arising out of or relating to this Agreement, the parties hereto shall consult and negotiate with each other and, recognizing their mutual interests, attempt to reach a solution satisfactory to both parties. If the parties do not reach settlement within a period of 60 days, any unresolved controversy or claim arising out of or relating to this Agreement shall proceed to binding arbitration under the Rules of Arbitration of the International Chamber of Commerce. The parties shall seek to mutually appoint an arbitrator. If the parties cannot agree on a single arbitrator, then there shall be three (3) arbitrators: one selected by each party, and a third selected by the first two. Arbitration will take place in one of the following cities as mutually agreed between the parties California (USA) or Singapore. If the parties are unable to agree to one of these cities, then the arbitration shall proceed in California. All negotiations and arbitration proceedings pursuant to this Section will be confidential and treated as compromise and settlement negotiations for purposes of all similar rules and codes of evidence of applicable legislation and jurisdictions. The language of the arbitration shall be English.

24. Jurisdiction
(a) This Agreement will be governed by and construed in accordance with the applicable laws of the State of Nevada, USA, without giving effect to the principles of that State relating to conflicts of laws. Each party irrevocably agrees that any legal action, suit or proceeding that is not otherwise subject to the arbitration provisions of Section 21 (Dispute Resolution) must be brought solely and exclusively in, and will be subject to the service of process and other applicable procedural rules of, the State or Federal court in Nevada, USA, and each party irrevocably submits to the sole and exclusive personal jurisdiction of the courts in Nevada, USA, generally and unconditionally, with respect to any action, suit or proceeding brought by it or against it by the other party. Notwithstanding the foregoing, DuoWorld may bring a claim for equitable relief in any court with proper jurisdiction.

(b) Notwithstanding the provisions of Section 21 (Dispute Resolution), nothing in this Agreement shall prevent either party from seeking injunctive relief with respect to a violation of intellectual property rights, confidentiality obligations or enforcement or recognition of any award or order in any appropriate jurisdiction.

25. Modification
(a) To the Products: DuoWorld reserves the right at any time and from time to time to make commercially reasonable updates and modification to the Products without prior notice, provided that you has subscribed with DuoWorld to be informed about such change and/or modification, DuoWorld will informed you. Any new features that augment or enhance the current Products, including the release of new tools and resources, shall be subject to this Terms of Service. You may terminate your use of the Products if the Terms are modified in a manner that substantially affects your rights in connection with use of the Products. Your continued use of the Products after any such changes shall constitute your consent to such changes. With respect to No-Charge Products, accepting the updated Agreement is required for you to continue using the No-Charge Products. You may be required to click through the updated Agreement to show your acceptance. If you do not agree to the updated Agreement after it becomes effective, you will no longer have a right to use No-Charge Products. For the avoidance of doubt, any Order is subject to the version of the Agreement in effect at the time of the Order.

(b) To the Agreement: You agree and DuoWorld reserves the right at any time and from time to time to change and/or modify the Terms of Service (or any part thereof) in the Agreement without prior notice. If the Agreement is modified during your License Term or Subscription Term, the modified version will be effective upon your next renewal of a License Term, Support and Maintenance term, or Subscription Term, as applicable. In this case, if you object to the updated Agreement, as your exclusive remedy, you may choose not to renew, including cancelling any terms set to auto-renew. DuoWorld will notify you of changers and/or modifications by posting updated versions on the DuoWorld Web Site. Your continued use of the DuoWorld Web Site and/or the Product shall be deemed to be your consent to such changers and/or modifications in the Terms of Service. You can review the most current version of the Terms of Service at any time at ……………….This Terms of Service is effective from ….

26. General Terms
(a) Notices: Any notice under this Agreement must be given in writing. DuoWorld may provide notice to you via email or through your account. DuoWorld notices to you will be deemed given upon the first business day after we send it. You may provide notice to DuoWorld by post to DuoWorld Inc., 170S, Green Valley Parkway, Suite 300, Henderson, Nevada 89012, United States of America. Your notices to us will be deemed given upon our receipt.

(b) Force Majeure: Neither party shall be liable to the other for any delay or failure to perform any obligation under this Agreement (except for a failure to pay fees) if the delay or failure is due to unforeseen events which are beyond the reasonable control of such party, such as a strike, blockade, war, act of terrorism, riot, natural disaster, failure or diminishment of power or telecommunications or data networks or services, or refusal of a license by a government agency.

(c) Assignment: You shall not assign this Agreement without our prior written consent. DuoWorld shall not unreasonably withhold our consent if the assignee agrees to be bound by the terms and conditions of this Agreement. DuoWorld may assign our rights and obligations under this Agreement (in whole or in part) without your consent.

(d) Prior Communication: This Agreement is the entire agreement between you and DuoWorld relating to the Products and supersedes all prior or contemporaneous oral or written communications, proposals and representations with respect to the Products or any other subject matter covered by this Agreement.

(e) Severability: If any provision of this Agreement is held to be void, invalid, unenforceable or illegal, the other provisions shall continue in full force and effect.

(f) Amendments by You: This Agreement may not be modified or amended by you without our written agreement (which may be withheld in our complete discretion without any requirement to provide any explanation). As used herein, “including” (and its variants) means “including without limitation” (and its variants).

(g) No Waiver: No failure or delay by the injured party to this Agreement in exercising any right, power or privilege hereunder shall operate as a waiver thereof, nor shall any single or partial exercise thereof preclude any other or further exercise thereof or the exercise of any right, power or privilege hereunder at law or equity.

(h) Relationship: The parties are independent contractors. This Agreement shall not be construed as constituting either party as a partner of the other or to create any other form of legal association that would give on party the express or implied right, power or authority to create any duty or obligation of the other party.

